### ISSUE TITLE
I'm not using docker-compose

### ISSUE THREAD

**Issue by wintercounter** [dzek69/docker-windows-notifier#5]
It's just one way to use Docker. Other watchers are not being tied to `docker-compose` and this should not be either.

**Comment by dzek69** [comment]
I'm really sorry, but this tool was designed to use docker-compose files from the beginnig and I am not planning to change this.

If there are other tools that works for you - I'd suggest just using them instead of this one.

As a workaround: you don't have to actually change your workflow to docker-compose, but you can create docker-compose file just to define how docker-windows-notifier should behave. Treat it like a config file for this tool :)
